/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040201
#define SWIGCSHARP

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_CGRender2D(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_CGRender2D(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_CGRender2D(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } } while (0)


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif



//#ifdef CGRENDERVIEW_EXPORTS
//#define CGRENDERVIEW_API __declspec(dllexport)
//#else
//#define CGRENDERVIEW_API __declspec(dllimport)
//#endif // CGRENDERVIEW_EXPORTS
//#include "testswig.h"

#include "RenderView.h"
#include "CGWindow.h"
#include "CGWindowsWindos.h"
#include "CGRenderType.h"
//namespace CGRender
//{
//	enum WindowType
//	{
//		Window_Main = 0,
//		Window_One = 1,
//		Window_unknow = 0xff
//	};
//}

enum CGRenderEventType_swig
{
	Event_Default = 0,
	Event_Rectangle = 1,
	Event_RectWindow,
	Event_MeasureDistance,
	EventType_unknow = 0xff,
};

using namespace CGRender;



#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void * SWIGSTDCALL CSharp_new_CGRenderView(void * jarg1, void * jarg2, void * jarg3) {
  void * jresult ;
  uint32_t arg1 ;
  uint32_t arg2 ;
  void *arg3 = (void *) 0 ;
  uint32_t *argp1 ;
  uint32_t *argp2 ;
  CGRender::CGRenderView *result = 0 ;
  
  argp1 = (uint32_t *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg1 = *argp1; 
  argp2 = (uint32_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null uint32_t", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (void *)jarg3; 
  result = (CGRender::CGRenderView *)new CGRender::CGRenderView(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_CGRenderView(void * jarg1) {
  CGRender::CGRenderView *arg1 = (CGRender::CGRenderView *) 0 ;
  
  arg1 = (CGRender::CGRenderView *)jarg1; 
  delete arg1;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_CGRenderView_createWindow(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  CGRender::CGRenderView *arg1 = (CGRender::CGRenderView *) 0 ;
  CGRender::WindowProps *arg2 = 0 ;
  bool result;
  
  arg1 = (CGRender::CGRenderView *)jarg1; 
  arg2 = (CGRender::WindowProps *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "CGRender::WindowProps const & is null", 0);
    return 0;
  } 
  result = (bool)(arg1)->createWindow((CGRender::WindowProps const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_CGRenderView_deleteWindow(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  CGRender::CGRenderView *arg1 = (CGRender::CGRenderView *) 0 ;
  std::wstring *arg2 = 0 ;
  bool result;
  
  arg1 = (CGRender::CGRenderView *)jarg1; 
  arg2 = (std::wstring *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::wstring const & is null", 0);
    return 0;
  } 
  result = (bool)(arg1)->deleteWindow((std::wstring const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_CGRenderView_getWindowByTitle(void * jarg1, void * jarg2) {
  void * jresult ;
  CGRender::CGRenderView *arg1 = (CGRender::CGRenderView *) 0 ;
  std::wstring *arg2 = 0 ;
  SwigValueWrapper< std::shared_ptr< CGRender::Window > > result;
  
  arg1 = (CGRender::CGRenderView *)jarg1; 
  arg2 = (std::wstring *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::wstring const & is null", 0);
    return 0;
  } 
  result = (arg1)->getWindowByTitle((std::wstring const &)*arg2);
  jresult = new std::shared_ptr< CGRender::Window >(result); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_CGRenderView_closeWindow(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  CGRender::CGRenderView *arg1 = (CGRender::CGRenderView *) 0 ;
  std::wstring *arg2 = 0 ;
  bool result;
  
  arg1 = (CGRender::CGRenderView *)jarg1; 
  arg2 = (std::wstring *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::wstring const & is null", 0);
    return 0;
  } 
  result = (bool)(arg1)->closeWindow((std::wstring const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_CGRenderView_Render(void * jarg1) {
  CGRender::CGRenderView *arg1 = (CGRender::CGRenderView *) 0 ;
  
  arg1 = (CGRender::CGRenderView *)jarg1; 
  (arg1)->Render();
}


SWIGEXPORT int SWIGSTDCALL CSharp_testswig_add(int jarg1, int jarg2) {
  int jresult ;
  int arg1 ;
  int arg2 ;
  int result;
  
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)testswig_add(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_g_windowMainStr_get() {
  void * jresult ;
  std::wstring result;
  
  result = (std::wstring)CGRender::g_windowMainStr;
  jresult = new std::wstring(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_WindowsWindow(void * jarg1) {
  void * jresult ;
  CGRender::WindowProps *arg1 = 0 ;
  CGRender::WindowsWindow *result = 0 ;
  
  arg1 = (CGRender::WindowProps *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "CGRender::WindowProps const & is null", 0);
    return 0;
  } 
  result = (CGRender::WindowsWindow *)new CGRender::WindowsWindow((CGRender::WindowProps const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_WindowsWindow(void * jarg1) {
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_WindowsWindow_Render(void * jarg1) {
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  (arg1)->Render();
}


SWIGEXPORT void * SWIGSTDCALL CSharp_WindowsWindow_GetWidth(void * jarg1) {
  void * jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  uint32_t result;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  result = ((CGRender::WindowsWindow const *)arg1)->GetWidth();
  jresult = new uint32_t(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_WindowsWindow_GetHeight(void * jarg1) {
  void * jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  uint32_t result;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  result = ((CGRender::WindowsWindow const *)arg1)->GetHeight();
  jresult = new uint32_t(result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_WindowsWindow_SetEventCallback(void * jarg1, void * jarg2) {
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  CGRender::Window::EventCallbackFn *arg2 = 0 ;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  arg2 = (CGRender::Window::EventCallbackFn *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "CGRender::Window::EventCallbackFn const & is null", 0);
    return ;
  } 
  (arg1)->SetEventCallback((CGRender::Window::EventCallbackFn const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_WindowsWindow_SetRenderViewCallback(void * jarg1, void * jarg2) {
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  CGRender::Window::RenderViewCallBackFn *arg2 = 0 ;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  arg2 = (CGRender::Window::RenderViewCallBackFn *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "CGRender::Window::RenderViewCallBackFn const & is null", 0);
    return ;
  } 
  (arg1)->SetRenderViewCallback((CGRender::Window::RenderViewCallBackFn const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_WindowsWindow_SetVSync(void * jarg1, unsigned int jarg2) {
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  bool arg2 ;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  arg2 = jarg2 ? true : false; 
  (arg1)->SetVSync(arg2);
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_WindowsWindow_IsVSync(void * jarg1) {
  unsigned int jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  bool result;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  result = (bool)((CGRender::WindowsWindow const *)arg1)->IsVSync();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_WindowsWindow_getType(void * jarg1) {
  void * jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  WindowType result;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  result = (arg1)->getType();
  jresult = new WindowType(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_WindowsWindow_GetNativeWindow(void * jarg1) {
  void * jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  void *result = 0 ;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  result = (void *)((CGRender::WindowsWindow const *)arg1)->GetNativeWindow();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_WindowsWindow_GetWindowHwnd(void * jarg1) {
  void * jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  void *result = 0 ;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  result = (void *)((CGRender::WindowsWindow const *)arg1)->GetWindowHwnd();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_WindowsWindow_OnWindowClose(void * jarg1) {
  unsigned int jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  bool result;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  result = (bool)(arg1)->OnWindowClose();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_WindowsWindow_addCGRenderEvent__SWIG_0(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  CGRender::CGRenderEvent *arg2 = (CGRender::CGRenderEvent *) 0 ;
  bool result;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  arg2 = (CGRender::CGRenderEvent *)jarg2; 
  result = (bool)(arg1)->addCGRenderEvent(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_WindowsWindow_addCGRenderEvent__SWIG_1(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  CGRenderEventType arg2 ;
  CGRenderEventType *argp2 ;
  bool result;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  argp2 = (CGRenderEventType *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null CGRenderEventType", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (bool)(arg1)->addCGRenderEvent(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_WindowsWindow_removeCGRenderEvent(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  CGRenderEventType arg2 ;
  CGRenderEventType *argp2 ;
  bool result;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  argp2 = (CGRenderEventType *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null CGRenderEventType", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (bool)(arg1)->removeCGRenderEvent(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_WindowsWindow_AfterEvent(void * jarg1) {
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  (arg1)->AfterEvent();
}


SWIGEXPORT int SWIGSTDCALL CSharp_WindowsWindow_ContextID(void * jarg1) {
  int jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  int result;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  result = (int)(arg1)->ContextID();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_WindowsWindow_getCamera(void * jarg1) {
  void * jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  CGRender::CGCamera *result = 0 ;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  result = (CGRender::CGCamera *)(arg1)->getCamera();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_WindowsWindow_getCurLayer(void * jarg1) {
  void * jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  CGData::CGLayer *result = 0 ;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  result = (CGData::CGLayer *)(arg1)->getCurLayer();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_WindowsWindow_getViewMatrix(void * jarg1) {
  void * jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  glm::mat4 result;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  result = ((CGRender::WindowsWindow const *)arg1)->getViewMatrix();
  jresult = new glm::mat4(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_WindowsWindow_getPerspectiveMatrix(void * jarg1) {
  void * jresult ;
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  glm::mat4 *result = 0 ;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  result = (glm::mat4 *) &(arg1)->getPerspectiveMatrix();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_WindowsWindow_addImage(void * jarg1, void * jarg2) {
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  std::wstring *arg2 = 0 ;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  arg2 = (std::wstring *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::wstring const & is null", 0);
    return ;
  } 
  (arg1)->addImage((std::wstring const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_WindowsWindow_syncWindowByParent(void * jarg1, void * jarg2) {
  CGRender::WindowsWindow *arg1 = (CGRender::WindowsWindow *) 0 ;
  CGRender::WindowsWindow *arg2 = (CGRender::WindowsWindow *) 0 ;
  
  arg1 = (CGRender::WindowsWindow *)jarg1; 
  arg2 = (CGRender::WindowsWindow *)jarg2; 
  (arg1)->syncWindowByParent(arg2);
}


#ifdef __cplusplus
}
#endif

