//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CGRender2D {
  public static int testswig_add(int a, int b) {
    int ret = CGRender2DPINVOKE.testswig_add(a, b);
    return ret;
  }

  public static SWIGTYPE_p_std__wstring g_windowMainStr {
    get {
      SWIGTYPE_p_std__wstring ret = new SWIGTYPE_p_std__wstring(CGRender2DPINVOKE.g_windowMainStr_get(), true);
      return ret;
    } 
  }

}
