//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CGRenderView : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CGRenderView(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CGRenderView obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CGRenderView obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CGRenderView() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CGRender2DPINVOKE.delete_CGRenderView(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CGRenderView(SWIGTYPE_p_uint32_t width, SWIGTYPE_p_uint32_t height, SWIGTYPE_p_void parent) : this(CGRender2DPINVOKE.new_CGRenderView(SWIGTYPE_p_uint32_t.getCPtr(width), SWIGTYPE_p_uint32_t.getCPtr(height), SWIGTYPE_p_void.getCPtr(parent)), true) {
    if (CGRender2DPINVOKE.SWIGPendingException.Pending) throw CGRender2DPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool createWindow(SWIGTYPE_p_CGRender__WindowProps windowsProps) {
    bool ret = CGRender2DPINVOKE.CGRenderView_createWindow(swigCPtr, SWIGTYPE_p_CGRender__WindowProps.getCPtr(windowsProps));
    if (CGRender2DPINVOKE.SWIGPendingException.Pending) throw CGRender2DPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool deleteWindow(SWIGTYPE_p_std__wstring title) {
    bool ret = CGRender2DPINVOKE.CGRenderView_deleteWindow(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(title));
    if (CGRender2DPINVOKE.SWIGPendingException.Pending) throw CGRender2DPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__shared_ptrT_CGRender__Window_t getWindowByTitle(SWIGTYPE_p_std__wstring title) {
    SWIGTYPE_p_std__shared_ptrT_CGRender__Window_t ret = new SWIGTYPE_p_std__shared_ptrT_CGRender__Window_t(CGRender2DPINVOKE.CGRenderView_getWindowByTitle(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(title)), true);
    if (CGRender2DPINVOKE.SWIGPendingException.Pending) throw CGRender2DPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool closeWindow(SWIGTYPE_p_std__wstring title) {
    bool ret = CGRender2DPINVOKE.CGRenderView_closeWindow(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(title));
    if (CGRender2DPINVOKE.SWIGPendingException.Pending) throw CGRender2DPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Render() {
    CGRender2DPINVOKE.CGRenderView_Render(swigCPtr);
  }

}
