//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class WindowsWindow : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal WindowsWindow(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(WindowsWindow obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(WindowsWindow obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~WindowsWindow() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CGRender2DPINVOKE.delete_WindowsWindow(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public WindowsWindow(SWIGTYPE_p_CGRender__WindowProps props) : this(CGRender2DPINVOKE.new_WindowsWindow(SWIGTYPE_p_CGRender__WindowProps.getCPtr(props)), true) {
    if (CGRender2DPINVOKE.SWIGPendingException.Pending) throw CGRender2DPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Render() {
    CGRender2DPINVOKE.WindowsWindow_Render(swigCPtr);
  }

  public SWIGTYPE_p_uint32_t GetWidth() {
    SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(CGRender2DPINVOKE.WindowsWindow_GetWidth(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_uint32_t GetHeight() {
    SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(CGRender2DPINVOKE.WindowsWindow_GetHeight(swigCPtr), true);
    return ret;
  }

  public void SetEventCallback(SWIGTYPE_p_CGRender__Window__EventCallbackFn callback) {
    CGRender2DPINVOKE.WindowsWindow_SetEventCallback(swigCPtr, SWIGTYPE_p_CGRender__Window__EventCallbackFn.getCPtr(callback));
    if (CGRender2DPINVOKE.SWIGPendingException.Pending) throw CGRender2DPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRenderViewCallback(SWIGTYPE_p_CGRender__Window__RenderViewCallBackFn callback) {
    CGRender2DPINVOKE.WindowsWindow_SetRenderViewCallback(swigCPtr, SWIGTYPE_p_CGRender__Window__RenderViewCallBackFn.getCPtr(callback));
    if (CGRender2DPINVOKE.SWIGPendingException.Pending) throw CGRender2DPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetVSync(bool enabled) {
    CGRender2DPINVOKE.WindowsWindow_SetVSync(swigCPtr, enabled);
  }

  public bool IsVSync() {
    bool ret = CGRender2DPINVOKE.WindowsWindow_IsVSync(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_WindowType getType() {
    SWIGTYPE_p_WindowType ret = new SWIGTYPE_p_WindowType(CGRender2DPINVOKE.WindowsWindow_getType(swigCPtr), true);
    return ret;
  }

  public virtual SWIGTYPE_p_void GetNativeWindow() {
    global::System.IntPtr cPtr = CGRender2DPINVOKE.WindowsWindow_GetNativeWindow(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public virtual SWIGTYPE_p_void GetWindowHwnd() {
    global::System.IntPtr cPtr = CGRender2DPINVOKE.WindowsWindow_GetWindowHwnd(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public bool OnWindowClose() {
    bool ret = CGRender2DPINVOKE.WindowsWindow_OnWindowClose(swigCPtr);
    return ret;
  }

  public virtual bool addCGRenderEvent(SWIGTYPE_p_CGRender__CGRenderEvent renderEvent) {
    bool ret = CGRender2DPINVOKE.WindowsWindow_addCGRenderEvent__SWIG_0(swigCPtr, SWIGTYPE_p_CGRender__CGRenderEvent.getCPtr(renderEvent));
    return ret;
  }

  public virtual bool addCGRenderEvent(SWIGTYPE_p_CGRenderEventType EventType) {
    bool ret = CGRender2DPINVOKE.WindowsWindow_addCGRenderEvent__SWIG_1(swigCPtr, SWIGTYPE_p_CGRenderEventType.getCPtr(EventType));
    if (CGRender2DPINVOKE.SWIGPendingException.Pending) throw CGRender2DPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool removeCGRenderEvent(SWIGTYPE_p_CGRenderEventType renderEventType) {
    bool ret = CGRender2DPINVOKE.WindowsWindow_removeCGRenderEvent(swigCPtr, SWIGTYPE_p_CGRenderEventType.getCPtr(renderEventType));
    if (CGRender2DPINVOKE.SWIGPendingException.Pending) throw CGRender2DPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void AfterEvent() {
    CGRender2DPINVOKE.WindowsWindow_AfterEvent(swigCPtr);
  }

  public int ContextID() {
    int ret = CGRender2DPINVOKE.WindowsWindow_ContextID(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_CGRender__CGCamera getCamera() {
    global::System.IntPtr cPtr = CGRender2DPINVOKE.WindowsWindow_getCamera(swigCPtr);
    SWIGTYPE_p_CGRender__CGCamera ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_CGRender__CGCamera(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_CGData__CGLayer getCurLayer() {
    global::System.IntPtr cPtr = CGRender2DPINVOKE.WindowsWindow_getCurLayer(swigCPtr);
    SWIGTYPE_p_CGData__CGLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_CGData__CGLayer(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_glm__mat4 getViewMatrix() {
    SWIGTYPE_p_glm__mat4 ret = new SWIGTYPE_p_glm__mat4(CGRender2DPINVOKE.WindowsWindow_getViewMatrix(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_glm__mat4 getPerspectiveMatrix() {
    SWIGTYPE_p_glm__mat4 ret = new SWIGTYPE_p_glm__mat4(CGRender2DPINVOKE.WindowsWindow_getPerspectiveMatrix(swigCPtr), false);
    return ret;
  }

  public void addImage(SWIGTYPE_p_std__wstring path) {
    CGRender2DPINVOKE.WindowsWindow_addImage(swigCPtr, SWIGTYPE_p_std__wstring.getCPtr(path));
    if (CGRender2DPINVOKE.SWIGPendingException.Pending) throw CGRender2DPINVOKE.SWIGPendingException.Retrieve();
  }

  public void syncWindowByParent(WindowsWindow parent) {
    CGRender2DPINVOKE.WindowsWindow_syncWindowByParent(swigCPtr, WindowsWindow.getCPtr(parent));
  }

}
